resources:
- name: logstash_git
  type: git
  source:
    uri: https://github.com/elastic/logstash.git
    branch: 5.x
- name: logstash_translate_plugin_concourse_ci
  type: git
  source:
    uri: https://github.com/stu-pete/logstash_translate_plugin_concourse.git
    branch: master
- name: s3_artifact_bucket
  type: s3
  source: 
    bucket: {{s3_bucket}}
    region_name: {{s3_region}} 
    access_key_id: {{s3_access_key}}
    secret_access_key: {{s3_secret_key}}
    versioned_file: logstash_latest.tar.gz
    private: true
  
jobs:
- name: logstash
  plan:
  - get: logstash_git
  - get: logstash_translate_plugin_concourse_ci


  - task: logstash_build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: jruby
          tag: "latest"


      inputs:
      - name: logstash_git
      - name: logstash_translate_plugin_concourse_ci
      run:
        path: logstash_translate_plugin_concourse_ci/task/logstash_build/run.sh
      outputs:
      - name: build_output/
        
  - put: s3_artifact_bucket
    params:
      file: build_output/logstash_latest.tar.gz
